export const ActivityTypes = {
  CREATED: "TICKET_CREATED",
  ASSIGNED: "TICKET_ASSIGNED",
  RESOLVED: "TICKET_RESOLVED",
  VERIFIED: "TICKET_VERIFIED",
  CLOSED: "TICKET_CLOSED",
  COMMENT_ADDED: "COMMENT_ADDED",
} as const;
