export const ActivityTypes = {
  CREATED: "TICKET_CREATED",
  ASSIGNED: "TICKET_ASSIGNED",
  RESOLVED: "TICKET_RESOLVED",
  VERIFIED: "TICKET_VERIFIED",
  CLOSED: "TICKET_CLOSED",
  COMMENT_ADDED: "COMMENT_ADDED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  STATUS_CHANGED: "STATUS_CHANGED",
  TYPE_CHANGED: "TYPE_CHANGED",
} as const;
